                                                Value
Stations in stable panel                          105
Stations with ICE/IC records before filtering      99
ICE/IC records before filtering                195426
ICE/IC records after filtering                 195153
Records excluded by station filter                273
Stable-panel stations with ICE/IC records          97

                 ICE/IC stop records
station_name
Weimar                           227
Berlin Ostkreuz                   46

,station_name,xml_station_name,eva,train_number,line_number,final_destination_station,delay_in_min,time,arrival_is_canceled,departure_is_canceled,...,is_additional_stop,is_replacement_train,replaced_train_number,train_line_ride_id,train_line_station_num,arrival_planned_time,arrival_change_time,departure_planned_time,departure_change_time,id
0,München Hbf,München Hbf,08000261,618,NaN,Kiel Hbf,0,2025-01-01 00:00:00,False,False,...,False,False,NaN,2686007473625185344,1,NaT,NaT,2025-01-01 00:00:00,2025-01-01 00:00:00,2686007473625185344-2501010000-1
1,Köln Hbf,Köln Hbf,08000207,619,NaN,München Hbf,6,2025-01-01 00:01:00,False,False,...,False,False,NaN,7474414276230536927,14,2024-12-31 23:49:00,2024-12-31 23:51:00,2024-12-31 23:55:00,2025-01-01 00:01:00,7474414276230536927-2412311838-14
2,Berlin Südkreuz,Berlin Südkreuz,08011113,805,NaN,Berlin Südkreuz,-1,2025-01-01 00:01:00,False,False,...,False,False,NaN,5554857220674495144,9,2025-01-01 00:02:00,2025-01-01 00:01:00,NaT,NaT,5554857220674495144-2412312134-9
3,Mannheim Hbf,Mannheim Hbf,08000244,775,NaN,Karlsruhe Hbf,2,2025-01-01 00:01:00,False,False,...,False,False,NaN,5181720942697741094,8,2024-12-31 23:56:00,2024-12-31 23:57:00,2024-12-31 23:59:00,2025-01-01 00:01:00,5181720942697741094-2412311833-8
4,Ulm Hbf,Ulm Hbf,08000170,1060,NaN,Stuttgart Hbf,0,2025-01-01 00:01:00,False,False,...,False,False,NaN,4747644076881825118,4,2024-12-31 23:59:00,2024-12-31 23:59:00,2025-01-01 00:01:00,2025-01-01 00:01:00,4747644076881825118-2412312245-4